/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pdf.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {
    @Test
    void encryptedPdf() {
        Library classUnderTest = new Library();
        assertFalse(classUnderTest.injectedPDF("/Users/sraguram/Downloads/2023_AnnualReviewTrustSummary.pdf"), 
            "encrypted pdf should return false");
    }

    @Test
    void simpleAction() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.injectedPDF("/Users/sraguram/Downloads/js_injected_Test.pdf"),
            "should return 'true'");
    }

    @Test
    void multipleActions() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.injectedPDF("/Users/sraguram/Downloads/js_injected_Test_2.pdf"),
            "should return 'true'");
    }
}
